#pragma once
#include "Expressions/UnaryOp.h"
#include "Expressions/Literal.h"
#include "Expressions/BinaryOp.h"
#include "Expressions/Grouping.h"
#include "Expressions/Factorial.h"
#include "Expressions/IncrementExpression.h"
#include "Expressions/DecrementExpression.h"

#include "Statements/Block.h"
#include "Statements/Program.h"
#include "Statements/IfStatement.h"
#include "Statements/PrintStatement.h"
#include "Statements/VariableDefinition.h"
#include "Statements/VariableAssignment.h"